### PR TITLE
Licensing tip doc back to word

### PR DESCRIPTION
**Pull request by lindsenC-gallagher**
.

### CODE REVIEW

**Review by Daniel-King-GGL — APPROVED** [review]
Added some comments to the doc

**Comment by lindsenC-gallagher** [comment]
@Daniel-King-GGL looks like you don't have write privileges to this repo :(

**Comment by lindsenC-gallagher** [comment]
@NadineWadi-Gallagher would you happen to have write privileges to this repo

**Comment by lindsenC-gallagher** [comment]
@andrewdonkin can I have merge privileges to this repo please.

**Review by AndrewDonkin-Gallagher — APPROVED** [review]

**Pull request merged**
