### PR TITLE
Licensing service TIP doc, update ccweb tip doc

### PR DESCRIPTION
**Pull request by lindsenC-gallagher**

### CODE REVIEW

**Comment by AndrewDonkin-Gallagher** [comment]
I reckon that we are happy with using github to distribute these things, you could switch from PDF to markdown.  It's easier - no need to export from a Word file you keep in another repo.

**Comment by AndrewDonkin-Gallagher** [comment]
whoops, reopening

**Review by AndrewDonkin-Gallagher — APPROVED** [review]
Reckon you should move to something easier to update than PDF.

**Comment by AndrewDonkin-Gallagher** [comment]
If you call it readme.md it will render in github, no need for the viewer person to do anything special.
Even though git and github are case-sensitive for filenames you can only have one of those per folder obviously, so that's a downside, but one folder per doc is okay by me.  Nicer URLs too.

**Comment by lindsenC-gallagher** [comment]
@AndrewDonkin-Gallagher I'm going to copy how we do it with https://[gallaghersecurity.github.io/mobileconnectsdk/releases.html](https://gallaghersecurity.github.io/mobileconnectsdk/releases.html), using jekyll to render the markdown into html

**Review by AndrewDonkin-Gallagher — APPROVED** [review]
I bet that PNG would be a fairly small SVG
:)

**Comment by AndrewDonkin-Gallagher** [comment]
> @AndrewDonkin-Gallagher Do you want to do it like https://[gallaghersecurity.github.io/mobileconnectsdk/releases.html](https://gallaghersecurity.github.io/mobileconnectsdk/releases.html), using jekyll to render the markdown into html or simply show the file preview in the github repo itself [directly](https://github.com/lindsenC-gallagher/gallaghersecurity.github.io/blob/licensing/docs/licensing-service/tip.md)?

a) it's not how I want to do it, it's up to you, but thanks for the ask.
b) I render asciidoc to HTML as a github action from github.com to [github.io](https://gallaghersecurity.github.io/cc-rest-docs/training/), like jekyll I guess but a different action, and it ends up very tidy.
c) But it's extra complication, and it slows down deployment.  I have to wait and faff around with clearing the browser cache before I can see changes.
d) This is the big one:  mine depends on containers that I should keep an eye on in case they get hacked.  Not sure if yours will.

So, I don't know.  I'd see how much Mermaid gets rendered on the fly by github.  If either github or the jekyll build handled more markdown than the other then I'd go with that one.  Especially mermaid's diagram types:  the PNG you have could be expressed in Mermaid which would be a lot easier to edit than the PNG (not sure if you could make it look as good, though).

**Comment by lindsenC-gallagher** [comment]
> it's not how I want to do it, it's up to you

if that is the case then I'll do something similar to [https://gallaghersecurity.github.io/mobileconnectsdk/releases.html](https://gallaghersecurity.github.io/mobileconnectsdk/releases.html). This just means I have to change the layout as currently it is hardcoded with `Mobile Credentials`. 

> I bet that PNG would be a fairly small SVG
Someone from marketing did this for me to make it consistent with the other diagrams. Mermaid is probably better.

> Mermaid 
I'll consider this when the diagram needs updating.

**Comment by lindsenC-gallagher** [comment]
Preview of what it looks like
image

**Comment by lindsenC-gallagher** [comment]
@AndrewDonkin-Gallagher I'm happy with this, please merge

**Review by AndrewDonkin-Gallagher — APPROVED** [review]

**Pull request merged**
